# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e40caa4a4066a903e93099062b840fa48a7f269e1e02b7d7333fed26f9db3360a01b6d08d21cb900d8206e81aa060e9b62a03ef0c959d3b128bd8bf42561e107

test:
  secret_key_base: c03302a258d4ab46dfef06cb9427306cac9d0566ab917708e3d52776bf47207664ea5bb6d6a9dd95e8fa2ed72319d7e36f81034fa70209e30fbb914d144be88d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
